name: Code Validation

on:
  push:
  pull_request:

jobs:
  cwtools:
    name: CWTools Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run CWTools for HOI4
        uses: cwtools/cwtools-action@v1.1.0
        with:
          game: hoi4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
